version: '3.4'

services:
  ccextra:
    image: jscoba/ccextra
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8000
    volumes:
      - ${PWD}/ccextra/ccextra/settings_mysql.py:/app/ccextra/settings.py:ro
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

